[package]
name = "template-rust-repo"
version = "0.0.1"
authors = ["First Last <user@email>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
